module.exports = {
  campaignPcAnimals: {
    0: [
      "Mosquito",
      "Bee",
      "Parrot",
      "Toad",
      "Salamander",
      "Ball bug",
      "Comb Star",
      "Lizard",
      "Frog",
      "Leech",
    ],
    450: [
      "Mosquito",
      "Bee",
      "Parrot",
      "Toad",
      "Hedgehog",
      "Bat",
      "Lizard",
      "Salamander",
      "Chameleon",
      "Electric Eel",
    ],
    900: [
      "Tortoise",
      "Bee",
      "Parrot",
      "Toad",
      "Swordfish",
      "Hedgehog",
      "Blowfish",
      "Electric Eel",
      "Pelican",
      "Lizard",
    ],
    1350: [
      "Salamander",
      "Bee",
      "Spider",
      "Toad",
      "Frog",
      "Basilisk Lizard",
      "Vulture",
      "Swordfish",
      "Leech",
      "Tortoise",
    ],
    1800: [
      "Mosquito",
      "Bee",
      "Spider",
      "Scorpion",
      "Ball bug",
      "Leech",
      "Bat",
      "Toad",
      "Eagle",
      "Frog",
    ],
    2250: [
      "Eagle",
      "Cassowary",
      "Parrot",
      "Ostrich",
      "Salamander",
      "Pelican",
      "Bat",
      "Cheetah",
      "Spider",
      "Stingray",
    ],
    2700: [
      "Swordfish",
      "Shark",
      "Stingray",
      "Blowfish",
      "Comb Star",
      "Orc",
      "Electric Eel",
      "Octopus",
      "Pelican",
      "Basilisk Lizard",
    ],
    3150: [
      "Chameleon",
      "Crocodile",
      "Komodo Dragon",
      "Snake",
      "Tortoise",
      "Alligator",
      "Lizard",
      "Basilisk Lizard",
      "Orc",
      "Elephant",
    ],
    3600: [
      "Lion",
      "Elephant",
      "Gorilla",
      "Cheetah",
      "Hyena",
      "Wolf",
      "Bear",
      "Shark",
      "Orc",
      "Little Lion",
    ],
  },
};
